# Generated by Django 5.1 on 2024-09-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='vikram@gmail.com', max_length=254),
        ),
    ]
