# Generated by Django 5.1 on 2024-09-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_webpage_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='Topic_name',
            new_name='topic_name',
        ),
    ]
